# Método iterativo de Jacobi

In [1]:
import numpy as np

In [17]:
def jacobi(A, b, x0, epsilon, kmax):
    x = np.matrix(x0)
    for k in range(kmax):
        x = np.concatenate((x, np.zeros((len(x0), 1))), axis=1)
        for i in range(len(x0)):
            sum_x = 0
            for j in range(len(x0)):
                if i != j:
                    sum_x += A[i, j] * x[j,k]
            x[i, k+1] = 1/A[i, i]*(-sum_x+b[i,0])
        verror = np.linalg.norm(x[:,k+1]-x[:,k]) # Check
        if verror < epsilon:
            return x[:, k+1]
    return x[:, kmax]

In [5]:
A = np.matrix([[9., -2., -1., 0., 3.], [0., 7., 3., -1., 0.], [1., -2., 8., 2., -1.],[1., -3., 1., 9., -1.], [4., -1., 2., -2., 10.]])
A

matrix([[ 9., -2., -1.,  0.,  3.],
        [ 0.,  7.,  3., -1.,  0.],
        [ 1., -2.,  8.,  2., -1.],
        [ 1., -3.,  1.,  9., -1.],
        [ 4., -1.,  2., -2., 10.]])

In [14]:
b = np.matrix([21., 0., 17., -3., 25.]).T
b

matrix([[21.],
        [ 0.],
        [17.],
        [-3.],
        [25.]])

In [7]:
x_0 = np.matrix([1., 1., 0., 1., 1.]).T
x_0

matrix([[1.],
        [1.],
        [0.],
        [1.],
        [1.]])

In [20]:
jacobi(A, b, x_0, 1e-8, 50)

matrix([[ 2.],
        [-1.],
        [ 2.],
        [-1.],
        [ 1.]])