# Jacobi

In [35]:
import numpy as np

In [36]:
def jacobi(A, b, x0, epsilon, kmax):
    x = np.copy(x0)
    for k in range(kmax):
        x = np.concatenate((x, np.zeros((len(x0), 1))), axis=1)
        for i in range(len(x0)):
            sum_x = 0
            for j in range(len(x0)):
                if i != j:
                    sum_x += A[i, j] * x[j,k]
            x[i, k+1] = 1/A[i, i]*(-sum_x+b[i,0])
        verror = np.linalg.norm(x[:,k+1]-x[:,k]) # Check
        if verror < epsilon:
            return x[:, k+1]
    return x[:, kmax]

In [37]:
A = np.array([[9., -2., -1., 0., 3.], [0., 7., 3., -1., 0.], [1., -2., 8., 2., -1.],[1., -3., 1., 9., -1.], [4., -1., 2., -2., 10.]])
A

array([[ 9., -2., -1.,  0.,  3.],
       [ 0.,  7.,  3., -1.,  0.],
       [ 1., -2.,  8.,  2., -1.],
       [ 1., -3.,  1.,  9., -1.],
       [ 4., -1.,  2., -2., 10.]])

In [38]:
b = np.array([[21., 0., 17., -3., 25.]]).T
b

array([[21.],
       [ 0.],
       [17.],
       [-3.],
       [25.]])

In [39]:
x_0 = np.array([[1., 1., 0., 1., 1.]]).T
x_0

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [40]:
sol_j = jacobi(A, b, x_0, 1e-8, 50)
sol_j

array([ 2., -1.,  2., -1.,  1.])

# Gauss-Seidel

In [41]:
def gauss_seidel(A, b, x0, epsilon, kmax):
    x = np.copy(x0)
    for k in range(kmax):
        x = np.concatenate((x, np.zeros((len(x0), 1))), axis=1)
        for i in range(len(x0)):
            sum_1, sum_2 = 0, 0
            for j in range(i):
                sum_1 += A[i, j] * x[j,k+1]
            for j in range(i+1, len(x0)):
                sum_2 += A[i, j] * x[j,k]
            x[i, k+1] = 1/A[i, i]*(-sum_1-sum_2+b[i,0])
        verror = np.linalg.norm(x[:,k+1]-x[:,k])
        if verror < epsilon:
            return x[:, k+1]
    return x[:, kmax]

In [42]:
A = np.array([[9., -2., -1., 0., 3.], [0., 7., 3., -1., 0.], [1., -2., 8., 2., -1.],[1., -3., 1., 9., -1.], [4., -1., 2., -2., 10.]])
A

array([[ 9., -2., -1.,  0.,  3.],
       [ 0.,  7.,  3., -1.,  0.],
       [ 1., -2.,  8.,  2., -1.],
       [ 1., -3.,  1.,  9., -1.],
       [ 4., -1.,  2., -2., 10.]])

In [43]:
b = np.array([[21., 0., 17., -3., 25.]]).T
b

array([[21.],
       [ 0.],
       [17.],
       [-3.],
       [25.]])

In [44]:
x_0 = np.array([[1., 1., 0., 1., 1.]]).T
x_0

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [45]:
sol_gs = gauss_seidel(A, b, x_0, 1e-8, 50)
sol_gs

array([ 2., -1.,  2., -1.,  1.])