# Dataframes

In [282]:
x <- data.frame(col1 = 1:5, col2 = base::c(TRUE, FALSE, FALSE, TRUE, FALSE))
x

col1 col2 
1 1     TRUE
2 2    FALSE
3 3    FALSE
4 4     TRUE
5 5    FALSE

In [283]:
nrow(x)

[1] 5

In [284]:
ncol(x)

[1] 2

In [285]:
x <- 12:15
x

[1] 12 13 14 15

In [286]:
names(x) <- base::c("doce", "trece", "catorce", "quince")
names(x)

[1] "doce"    "trece"   "catorce" "quince"

In [287]:
x

doce   trece catorce  quince 
     12      13      14      15

In [288]:
y <- list(1, 2, 3)
names(y) <- base::c("uno", "dos", "tres")
y

$uno
[1] 1

$dos
[1] 2

$tres
[1] 3

In [289]:
x["doce"]

doce 
  12

In [290]:
y$uno

[1] 1

In [291]:
m <- matrix(5:8, nrow = 2, ncol = 2)
dimnames(m) <- list(base::c("x", "y"), base::c("i", "j"))
m

i j
x 5 7
y 6 8

## Operaciones vectorizadas

In [292]:
x <- 5:8
y <- 11:14
x

[1] 5 6 7 8

In [293]:
y

[1] 11 12 13 14

In [294]:
x + y

[1] 16 18 20 22

In [295]:
x * y

[1]  55  72  91 112

In [296]:
x %*% y # Producto punto

[,1]
[1,] 330

In [297]:
3.5 * x

[1] 17.5 21.0 24.5 28.0

In [298]:
7 > x

[1]  TRUE  TRUE FALSE FALSE

In [299]:
13 == y

[1] FALSE FALSE  TRUE FALSE

In [300]:
x <- 1:10
x[4]

[1] 4

In [301]:
x[3:6]

[1] 3 4 5 6

In [302]:
ind <- x > 5
x[ind]

[1]  6  7  8  9 10

In [303]:
x[x > 5]

[1]  6  7  8  9 10

In [304]:
m <- matrix(11:20, 2, 5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 11   13   15   17   19  
[2,] 12   14   16   18   20

In [305]:
m[2, 5]

[1] 20

In [306]:
m[2, ]

[1] 12 14 16 18 20

In [307]:
m[, 3]

[1] 15 16

In [308]:
x <- list(hola = 1:10, mundo = 1 + 1i)
# Las listas pueden tener elementos de tipos distintos
x

$hola
 [1]  1  2  3  4  5  6  7  8  9 10

$mundo
[1] 1+1i

In [309]:
x$mundo

[1] 1+1i

In [310]:
x[1]

$hola
 [1]  1  2  3  4  5  6  7  8  9 10

In [311]:
x[[1]]

[1]  1  2  3  4  5  6  7  8  9 10

In [312]:
x$hola

[1]  1  2  3  4  5  6  7  8  9 10

In [313]:
x <- list(a = list(10, "a"), b = base::c(2.5, 8.1))
x

$a
$a[[1]]
[1] 10

$a[[2]]
[1] "a"


$b
[1] 2.5 8.1

In [314]:
x[[base::c(1, 2)]]

[1] "a"

In [315]:
x$a[2]

[[1]]
[1] "a"

In [316]:
x <- base::c(a = list(10, "a"), b = base::c(2.5, 8.1))
x

$a1
[1] 10

$a2
[1] "a"

$b1
[1] 2.5

$b2
[1] 8.1

In [317]:
x <- data.frame(12, NA, NA, 42, NA, 64)
falta <- is.na(x)
falta

X12   NA.  NA..1 X42   NA..2 X64  
[1,] FALSE TRUE TRUE  FALSE TRUE  FALSE

In [318]:
x[!is.na(x)]

[1] 12 42 64

In [319]:
x <- base::c(x1 = base::c(7, 3, 4, NA, 9),
       x2 = base::c(1, 4, 5, 7, NA),
       x3 = base::c(NA, 8, 8, NA, 3))
x

x11 x12 x13 x14 x15 x21 x22 x23 x24 x25 x31 x32 x33 x34 x35 
  7   3   4  NA   9   1   4   5   7  NA  NA   8   8  NA   3

In [320]:
complete.cases(x)

[1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE
[13]  TRUE FALSE  TRUE

In [321]:
x[complete.cases(x)]

x11 x12 x13 x15 x21 x22 x23 x24 x32 x33 x35 
  7   3   4   9   1   4   5   7   8   8   3

## Funciones

In [322]:
# nombre <- function(params){
#   operaciones
# }
doble <- function(x) {
  2 * x
}

doble(5)

[1] 10

In [323]:
formals(matrix) # Devuelve los parametros de una función

$data
[1] NA

$nrow
[1] 1

$ncol
[1] 1

$byrow
[1] FALSE

$dimnames
NULL


In [324]:
matrix(1:6, 2, 3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [325]:
matrix(ncol = 3, data = 1:6, nrow = 2)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## Parámetros perezosos

In [326]:
suc <- function(x, y) {
  x + 1
}
suc(5)

[1] 6

In [327]:
inc <- function(x, y) {
  if (x < 3) {
    x + 1
  } else {
    x + y
  }
}

inc(2)

[1] 3

In [328]:
inc(4, 2)

[1] 6

In [329]:
mayores <- function(vec, umb = 0) {
  ind <- vec > umb
  vec[ind]
}

mayores(1:20, 5)

[1]  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [330]:
mayores_pares <- function(vec, umb = 0) {
  vec[vec > umb & !bitwAnd(vec, 1)]
}

mayores_pares(1:20, 4)

[1]  6  8 10 12 14 16 18 20

In [331]:
# Suma los elementos de las columnas de una matriz
suma_cols <- function(matriz) {
  n_cols <- ncol(matriz)
  n_fils <- nrow(matriz)
  suma_col <- numeric(n_cols)
  for (j in 1:n_cols) {
    for (i in 1:n_fils) {
      suma_col[j] <- suma_col[j] + matriz[i, j]
    }
  }
  suma_col
}

suma_cols(matrix(1:20, 4, 5))

[1] 10 26 42 58 74

In [332]:
matrix(1:20, 4, 5)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [333]:
suma_cols <- function(matriz) {
  n_col <- ncol(matriz)
  suma_col <- numeric(n_col)
  for (j in 1:n_col) {
    suma_col[j] <- sum(matriz[, j])
  }
  suma_col
}

suma_cols(matrix(1:20, 4, 5))

[1] 10 26 42 58 74

In [334]:
c <- 5
c

[1] 5

In [335]:
c(1, 2, 3, 4, 5)

[1] 1 2 3 4 5

In [336]:
c

[1] 5

In [337]:
c <- function() {
  "Hola"
}

base::c(1, 2, 3, 4)

[1] 1 2 3 4

## Archivos

In [338]:
datos <- read.table("https://bit.ly/3c3C1iH", header = TRUE)
datos

FamilyNames FamilyAges FamilyGenders FamilyWeights
1 Dad         43         Male          188          
2 Mom         42         Female        136          
3 Sis         12         Female         83          
4 Bro          8         Male           61          
5 Dog          5         Female         44

In [339]:
cat <- base::c("Cat", 2, "Male", 10)
datos <- rbind(datos, cat)
write.table(datos, file = "family.txt", row.names = FALSE, quote = FALSE)